// Generated by CoffeeScript 1.4.0
(function() {
  var ArchiveBFile, PostBFile, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PostBFile = require('./PostBFile');

  ArchiveBFile = (function(_super) {

    __extends(ArchiveBFile, _super);

    function ArchiveBFile(pwd, encoding) {
      this.pwd = pwd;
      this.encoding = encoding;
      ArchiveBFile.__super__.constructor.call(this, this.pwd, this.encoding);
      this.type = 'archive';
    }

    ArchiveBFile.prototype.toUrl = function() {
      return ArchiveBFile.__super__.toUrl.call(this) + '/';
    };

    return ArchiveBFile;

  })(PostBFile);

  exports = ArchiveBFile;

}).call(this);
