// Generated by CoffeeScript 1.4.0
(function() {

  exports.parse = function(args) {
    var opt, req,
      _this = this;
    opt = [];
    req = [];
    args.forEach(function(value) {
      if (value[0] === '-') {
        return opt.push(value.slice(1));
      } else {
        return req.push(value);
      }
    });
    return {
      opt: opt,
      req: req
    };
  };

}).call(this);
