// Generated by CoffeeScript 1.4.0
(function() {
  var clc, util;

  util = require('util');

  clc = require('cli-color');

  module.exports = {
    help: function(args) {
      return require('./usage.js').help();
    },
    deploy: function(args) {
      return util.puts('This methods was not implemented');
    },
    server: function(args) {
      return require('./server.js');
    },
    update: function(args) {
      return require('./update.js')(args);
    },
    post: function(args) {
      return require('./post.js')(args);
    },
    page: function(args) {
      return require('./page.js')(args);
    },
    init: function(args) {
      return util.puts('This methods was not implemented');
    }
  };

}).call(this);
