// Generated by CoffeeScript 1.4.0
(function() {
  var clc, util;

  util = require('util');

  clc = require('cli-color');

  process.title = 'blogin';

  module.exports = {
    help: function(args) {
      return require('./usage.js').help(args);
    },
    deploy: function(args) {
      return require('./deploy')(args);
    },
    server: function(args) {
      return require('./server.js');
    },
    update: function(args) {
      return require('./update.js')(args);
    },
    post: function(args) {
      return require('./post.js')(args);
    },
    page: function(args) {
      return require('./page.js')(args);
    },
    init: function(args) {
      return require('./init')(args);
    },
    trash: function(args) {
      return require('./trash')(args);
    }
  };

}).call(this);
