// Generated by CoffeeScript 1.4.0
(function() {
  var MyUtil, exec, moment, parseArg, path, projectDir, usage, util;

  path = require('path');

  moment = require('moment');

  util = require('util');

  parseArg = require('./arg').parse;

  MyUtil = require('./MyUtil');

  usage = require('./usage');

  projectDir = './';

  exec = function(command, args, callback) {
    return MyUtil.spawn({
      command: command,
      args: args,
      options: {
        cwd: projectDir
      },
      exit: function(code) {
        if (code === 0 && callback) {
          return callback();
        }
      }
    });
  };

  module.exports = function(args) {
    var arg,
      _this = this;
    arg = parseArg(args);
    projectDir = path.resolve(process.cwd(), arg.req[0] || './');
    if (!MyUtil.checkProjectDir(projectDir)) {
      usage.puts('deploy');
      return;
    }
    return exec('git', ['add', '-A'], function() {
      var msg;
      msg = 'Update:' + moment().format('YYYY-MM-DD hh:mm:ss');
      args = ['commit', '-m', msg];
      return exec('git', args, function() {
        return exec('git', ['push'], function() {
          return util.puts('Deploy complete.');
        });
      });
    });
  };

}).call(this);
