// Generated by CoffeeScript 1.4.0
(function() {
  var newPost, parseArg, usage;

  newPost = require('./post');

  usage = require('./usage');

  parseArg = require('./arg').parse;

  module.exports = function(args) {
    var arg;
    arg = parseArg(args);
    if ((args.length === 0) || (arg.req.length === 0)) {
      usage.puts('pages');
      return;
    }
    return newPost(args, './data/pages/');
  };

}).call(this);
