// Generated by CoffeeScript 1.4.0
(function() {
  var newFile, parseArg, usage;

  newFile = require('./post');

  usage = require('./usage');

  parseArg = require('./arg').parse;

  module.exports = function(args) {
    var arg, filename, type;
    type = 'page';
    arg = parseArg(args);
    if (args.length === 0) {
      newFile.listFile(type);
      return;
    }
    if (arg.req.length === 0) {
      usage.puts(type);
      return;
    }
    filename = file.titleToPath(arg.req);
    return newFile(arg, filename, './data/pages/', 'page');
  };

}).call(this);
