// Generated by CoffeeScript 1.4.0
(function() {
  var file, parseArg, post, usage;

  post = require('./post');

  usage = require('./usage');

  parseArg = require('./arg').parse;

  file = require('./file');

  module.exports = function(args) {
    var arg, filename, type;
    type = 'page';
    arg = parseArg(args);
    if (args.length === 0) {
      post.listFile(type);
      return;
    }
    if (arg.req.length === 0) {
      usage.puts(type);
      return;
    }
    filename = file.titleToPath(arg.req);
    return post.newFile(arg, filename, 'page');
  };

}).call(this);
