// Generated by CoffeeScript 1.4.0
(function() {
  var PageBFile, PostBFile, exports,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PostBFile = require('./PostBFile');

  PageBFile = (function(_super) {

    __extends(PageBFile, _super);

    function PageBFile(pwd, encoding) {
      this.pwd = pwd;
      this.encoding = encoding;
      PageBFile.__super__.constructor.call(this, this.pwd, this.encoding);
      this.type = 'page';
    }

    return PageBFile;

  })(PostBFile);

  exports = PageBFile;

}).call(this);
