// Generated by CoffeeScript 1.4.0
(function() {
  var PathApi, exports, path;

  path = require('path');

  PathApi = {
    templateDir: './public/template/',
    projectDir: './',
    getJadeFile: function(type) {
      return path.resolve(this.templateDir, type + '.jade');
    },
    getSrcFile: function(type) {
      switch (type) {
        case 'page':
          return path.resolve(this.projectDir, 'data/pages');
        default:
          return path.resolve(this.projectDir, 'data/posts');
      }
    },
    getDestFile: function(type) {
      switch (type) {
        case 'archive':
          return path.resolve(this.projectDir, 'post');
        case 'post':
          return path.resolve(this.projectDir, 'post');
        case 'page':
          return path.resolve(this.projectDir, 'page');
        default:
          return path.resolve(this.projectDir, 'index.html');
      }
    },
    toUrl: function(filePath) {
      return '/' + path.relative(this.projectDir, filePath);
    }
  };

  exports = PathApi;

}).call(this);
