// Generated by CoffeeScript 1.4.0
(function() {
  var MyUtil, dirnameMap, file, moment, newFile, parseArg, usage, util;

  util = require('util');

  moment = require('moment');

  file = require('./file');

  usage = require('./usage');

  parseArg = require('./arg').parse;

  MyUtil = require('./MyUtil');

  dirnameMap = {
    post: './data/posts/{year}/',
    page: './data/pages/{year}/'
  };

  module.exports = function(args) {
    var arg, filename;
    arg = parseArg(args);
    if ((args.length === 0) || (arg.req.length === 0)) {
      usage.puts('post');
      return;
    }
    filename = file.titleToPath(arg.req);
    if (filename === 'index.md') {
      usage.puts('post');
      return;
    }
    return newFile(arg, filename, 'post');
  };

  newFile = module.exports.newFile = function(arg, filename, type) {
    var content, dataFile, dirname, postTitle;
    postTitle = arg.req.join(' ');
    content = postTitle + '\n======\n';
    dirname = dirnameMap[type].replace('{year}', moment().format('YYYY'));
    dataFile = dirname + filename;
    if (~arg.opt.indexOf('f')) {
      file.write(dataFile, content);
      util.puts('Created at ' + dataFile);
      return MyUtil.addInfo(type, dataFile);
    } else {
      if (file.writeIfNotExist(dataFile, content)) {
        util.puts('Created at ' + dataFile);
        return MyUtil.addInfo(type, dataFile);
      } else {
        return util.puts('Fail to create, file "' + dataFile + '" was existed.\nUse [-f] option to rewrite the file.');
      }
    }
  };

}).call(this);
