// Generated by CoffeeScript 1.4.0
(function() {
  var file, moment, parseArg, usage, util;

  util = require('util');

  moment = require('moment');

  file = require('./file');

  usage = require('./usage');

  parseArg = require('./arg').parse;

  module.exports = function(args, dirname) {
    var arg, content, dataFile, filename, postTitle;
    arg = parseArg(args);
    if ((args.length === 0) || (arg.req.length === 0)) {
      usage.puts('post');
      return;
    }
    filename = file.titleToPath(arg.req);
    if (filename === 'index.md') {
      usage.puts('post');
      return;
    }
    postTitle = arg.req.join(' ');
    content = postTitle + '\n======\n';
    dirname = (dirname || './data/posts/{year}/').replace('{year}', moment().format('YYYY'));
    dataFile = dirname + filename;
    if (~arg.opt.indexOf('f')) {
      file.write(dataFile, content);
      return util.puts('Created at ' + dataFile);
    } else {
      if (file.writeIfNotExist(dataFile, content)) {
        return util.puts('Created at ' + dataFile);
      } else {
        return util.puts('Fail to create, file "' + dataFile + '" was existed.\nUse [-f] option to rewrite the file.');
      }
    }
  };

}).call(this);
